Importing necessary libraries

In [153]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

Importing the Dataset

In [154]:
data=pd.read_csv('/content/iris.csv')

In [155]:
data.head()


sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [156]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [157]:
data.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [158]:
feature_columns=['sepal_length','sepal_width','petal_length','petal_width']

In [159]:
X=data[feature_columns]

In [160]:
data.species

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [161]:
y=data['species']

In [162]:
lb=LabelEncoder()

In [163]:
print('Iris-setosa:\n', y[0:10])
print('\n')
print('Iris-versicolour:\n', y[50:60])
print('\n')
print('Iris-virginica:\n', y[100:110])

Iris-setosa:
 0    setosa
1    setosa
2    setosa
3    setosa
4    setosa
5    setosa
6    setosa
7    setosa
8    setosa
9    setosa
Name: species, dtype: object


Iris-versicolour:
 50    versicolor
51    versicolor
52    versicolor
53    versicolor
54    versicolor
55    versicolor
56    versicolor
57    versicolor
58    versicolor
59    versicolor
Name: species, dtype: object


Iris-virginica:
 100    virginica
101    virginica
102    virginica
103    virginica
104    virginica
105    virginica
106    virginica
107    virginica
108    virginica
109    virginica
Name: species, dtype: object


In [164]:
y=lb.fit_transform(y)

In [165]:
print('Iris-setosa:\n', y[0:10])
print('\n')
print('Iris-versicolour:\n', y[50:60])
print('\n')
print('Iris-virginica:\n', y[100:110])

Iris-setosa:
 [0 0 0 0 0 0 0 0 0 0]


Iris-versicolour:
 [1 1 1 1 1 1 1 1 1 1]


Iris-virginica:
 [2 2 2 2 2 2 2 2 2 2]


In [166]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=4)

In [167]:
X_train

sepal_length  sepal_width  petal_length  petal_width
6             4.6          3.4           1.4          0.3
88            5.6          3.0           4.1          1.3
39            5.1          3.4           1.5          0.2
74            6.4          2.9           4.3          1.3
112           6.8          3.0           5.5          2.1
..            ...          ...           ...          ...
50            7.0          3.2           4.7          1.4
87            6.3          2.3           4.4          1.3
104           6.5          3.0           5.8          2.2
129           7.2          3.0           5.8          1.6
122           7.7          2.8           6.7          2.0

[90 rows x 4 columns]

In [168]:
X_test.head()

sepal_length  sepal_width  petal_length  petal_width
128           6.4          2.8           5.6          2.1
18            5.7          3.8           1.7          0.3
130           7.4          2.8           6.1          1.9
105           7.6          3.0           6.6          2.1
107           7.3          2.9           6.3          1.8

In [169]:
def knn_model(X_train,y_train,X_test,k):
    knn=KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train,y_train)
    y_pred=knn.predict(X_test)
    return y_pred

The accuracy of the model is decreasing as I increase the value of K

50 is the ideal valu:e  

In [170]:
y_pred=knn_model(X_train,y_train,X_test,k=50)

In [171]:
y_pred

array([2, 0, 2, 2, 2, 1, 1, 0, 0, 2, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 2,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 2, 0, 1, 2, 2, 1, 1, 0, 2, 0, 1, 0,
       2, 0, 0, 1, 1, 2, 0, 1, 2, 2, 1, 1, 0, 1, 1, 1])

In [172]:
accuracy_sklearn = accuracy_score(y_test, y_pred)*100

In [173]:
print('Model Accuracy:',accuracy_sklearn)

Model Accuracy: 93.33333333333333
